app/home/forms.py
# Forms for admin blueprint
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,IntegerField,FloatField
from wtforms.validators import DataRequired


class AlimentoForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    codigo = StringField('Codigo', validators=[DataRequired()])
    tipo = StringField('Tipo', validators=[DataRequired()])
    categoria = StringField('Categoria')
    proveedor = StringField('Proveedor', validators=[DataRequired()])
    descripcion = StringField('Descripcion', validators=[DataRequired()])
    kg = StringField('Peso')
    precio = FloatField('Precio')
    ean = StringField('ean')
    arriba = IntegerField('Local')
    abajo = IntegerField('Deposito')
    submit = SubmitField('Submit')

class EanForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    ean = StringField('EAN', validators=[DataRequired()])
    producto = StringField('Description')
    codigo = StringField('Codigo')
    submit = SubmitField('Submit')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, flash, redirect, render_template, url_for,jsonify,request,send_file
from flask_login import current_user, login_required
import pandas as pd
from sqlalchemy.inspection import inspect
from xlsxwriter import Workbook
#import flask_excel as excel

from . import home

from .forms import AlimentoForm,EanForm
from .. import db
from ..models import Alimento, Venta
from datetime import datetime

def query_to_list(rset):
    """List of result
    Return: columns name, list of result
    """
    result = []
    for obj in rset:
        instance = inspect(obj)
        items = instance.attrs.items()
        result.append([x.value for _,x in items])
    return instance.attrs.keys(), result
@home.route('/')
def homepage():
    """
    Render the homepage template on the / route adslangldsng l
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/alimentos', methods=['GET', 'POST'])
def list_alimentos():
    """
    List all alimentos
    """

    alimentos = Alimento.query.all()

    return render_template('home/alimentos/alimentos.html',
                           alimentos=alimentos, title="Alimento")


@home.route('/alimentos/add', methods=['GET', 'POST'])
def add_alimento():
    """
    Add a alimento to the database
    """
    add_alimento = True

    form = AlimentoForm()
    if form.validate_on_submit():
        alimento = Alimento(tipo = form.tipo.data,codigo = form.codigo.data
                                ,categoria = form.categoria.data,proveedor = form.proveedor.data,descripcion = form.descripcion.data
                                ,kg = form.kg.data,precio = form.precio.data,ean = form.ean.data,arriba = form.arriba.data
                                ,abajo = form.abajo.data)
        try:
            # add alimento to the database
            db.session.add(alimento)
            db.session.commit()
            flash('You have successfully added a new alimento.')
        except:
            # in case alimento name already exists
            flash('Error: alimento name already exists.')

        # redirect to alimentos page
        return redirect(url_for('home.list_alimentos'))

    # load alimento template
    return render_template('home/alimentos/alimento.html', action="Add",
                           add_alimento=add_alimento, form=form,
                           title="Add alimento")


@home.route('/alimentos/edit/<id>', methods=['GET', 'POST'])
def edit_alimento(id):
    """
    Edit a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    form = AlimentoForm(obj=alimento)
    if form.validate_on_submit():
        alimento.tipo = form.tipo.data
        alimento.categoria = form.categoria.data
        alimento.proveedor = form.proveedor.data
        alimento.descripcion = form.descripcion.data
        alimento.kg = form.kg.data
        alimento.precio = form.precio.data
        alimento.ean = form.ean.data
        alimento.arriba = form.arriba.data
        alimento.abajo = form.abajo.data
        db.session.commit()
        flash('You have successfully edited the alimento.')

        # redirect to the alimentos page
        return redirect(url_for('home.list_alimentos'))

    form.tipo.data=alimento.tipo
    form.categoria.data= alimento.categoria
    form.proveedor.data= alimento.proveedor
    form.descripcion.data= alimento.descripcion
    form.kg.data= alimento.kg
    form.precio.data= alimento.precio
    form.ean.data= alimento.ean
    form.arriba.data= alimento.arriba
    form.abajo.data= alimento.abajo
    return render_template('home/alimentos/alimento.html', action="Edit",
                           add_alimento=add_alimento, form=form,
                           alimento=alimento, title="Edit alimento")


@home.route('/alimentos/delete/<id>', methods=['GET', 'POST'])
def delete_alimento(id):
    """
    Delete a alimento from the database
    """
    check_home()

    alimento = alimento.query.get_or_404(id)
    db.session.delete(alimento)
    db.session.commit()
    flash('You have successfully deleted the alimento.')

    # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

    return render_template(title="Delete alimento")


@home.route('/alimentos/inventario/<id>', methods=['GET', 'POST'])
def mover_alimento(id):
    """
    Edit a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    alimento.arriba = int(alimento.arriba)+1
    alimento.abajo = int(alimento.abajo)-1
    db.session.commit()
    flash('You have successfully edited the alimento.')

        # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

@home.route('/alimentos/vender/<id>', methods=['GET', 'POST'])
def vender_alimento(id):
    """
    Vender a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    if alimento.arriba >0:
        alimento.arriba = int(alimento.arriba)-1
    else:
        alimento.abajo = int(alimento.abajo)-1
    db.session.commit()

    venta = Venta(codigo=id,tipo =alimento.tipo,    categoria = alimento.categoria,    proveedor = alimento.proveedor,    descripcion = alimento.descripcion,    kg = alimento.kg,    precio = alimento.precio,    ean = alimento.ean)
    try:
        # add alimento to the database
        db.session.add(venta)
        db.session.commit()
        flash('You have successfully added a new venta.')
    except Exception as inst :
        # in case alimento name already exists
        print(str(inst))
        flash('Error: no se pudo procesar la venta')

        # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

@home.route('/alimentos/ean/', methods=['GET', 'POST'])
def add_ean():
    """
    Add a alimento to the database
    """
    if request.method == 'POST':
        alimento = Alimento.query.get_or_404(id)
        alimento.ean = request.values.get('ean')
        db.session.commit()
        flash('You have successfully edited the alimento.')

    # load alimento template
    return render_template('home/alimentos/ean.html',
                           title="Agregar Ean")
@home.route('/alimentos/busqueda', methods=['GET', 'POST'])
def busqueda():
    if request.args.get('codigo') != None and len(request.args.get('codigo') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.codigo.like("%"+request.args.get('codigo')+"%")).all())
    elif request.args.get('descripcion') != None and len(request.args.get('descripcion') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.descripcion.like("%"+request.args.get('descripcion')+"%")).all())
    else:
        #names, data = query_to_list(Alimento.query.all())
        return  jsonify({"total": 0,'rows':[]})
    df = pd.DataFrame.from_records(data, columns=names)
    output=df[['descripcion', 'codigo', 'tipo', 'arriba', 'abajo','proveedor','precio','kg','categoria']].to_dict('records')
    return  jsonify({"total": len(output), "totalNotFiltered": 800,'rows':output})


@home.route('/alimentos/stock', methods=['GET', 'POST'])
def update_stock():
    if request.args.get('codigo') != None and len(request.args.get('codigo') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.codigo.like("%"+request.args.get('codigo')+"%")).all())
    elif request.args.get('descripcion') != None and len(request.args.get('descripcion') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.descripcion.like("%"+request.args.get('descripcion')+"%")).all())
    else:
        #names, data = query_to_list(Alimento.query.all())
        return  jsonify({"total": 0,'rows':[]})
    df = pd.DataFrame.from_records(data, columns=names)
    output=df[['descripcion', 'codigo', 'tipo', 'arriba', 'abajo','proveedor','precio','kg','categoria']].to_dict('records')
    return  jsonify({"total": len(output), "totalNotFiltered": 800,'rows':output})

@home.route('/alimentos/subir', methods=['GET','POST'])
def subir_productos():
    if request.method == 'POST':
        df=pd.DataFrame.from_dict(request.get_array(field_name='file'))
        df.columns=df.iloc[0]
        df=df.drop(0)
        df.set_index('codigo',inplace=True)
        df.to_sql('alimento', if_exists='replace',con=db.engine)
        return redirect(url_for('home.list_alimentos'))

        return jsonify({"result":request.get_array(field_name='file')})
    return '''
    <!doctype html>
    <title>Upload an excel file</title>
    <h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    <form action="" method=post enctype=multipart/form-data><p>
    <input type=file name=file><input type=submit value=Upload>
    </form>
    '''

@home.route('/alimentos/descargar', methods=['GET','POST'])
def descargar_productos():
    now = datetime.now()
    # return excel.make_response_from_tables(db.session,[Alimento,Venta],'xlsx',file_name='productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")))
    result = db.engine.execute("select * from alimento")
    df=pd.DataFrame(result.fetchall())
    writer1 = pd.ExcelWriter('productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")), engine='xlsxwriter')
    df.to_excel(writer1, sheet_name='name of sheet 1', index=False, startrow=0)
    writer1.save()
    return send_file('../productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")))

    #
@home.route('/alimentos/buscar', methods=['GET', 'POST'])
def buscar():

    return render_template('home/alimentos/buscar.html',
                           title="Buscar")

app/templates/home/alimentos/alimento.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_alimento %}
        Agregar Producto
    {% else %}
        Editar Producto
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_producto %}
                <h1>Add Alimento</h1>
            {% else %}
                <h1>Edit Alimento</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/alimentos/alimentos.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}alimentos{% endblock %}
{% block custom_css %}
<link   rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.min.css">
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">alimentos</h1>
        {% if alimentos %}
          <!-- <hr class="intro-divider"> -->
          <div class="center" style='width:75%'>
            <table
                 id="table"
                 data-toolbar="#toolbar"
             data-show-refresh="true"
             data-show-toggle="true"
             data-show-fullscreen="true"
             data-show-columns="true"
             data-show-export="true"
                 data-minimum-count-columns="2"
              data-show-pagination-switch="true"
                 data-filter-control="true"
                 data-pagination="true"
                 data-page-list="[10, 25, 50, 100, ALL]">
                 <thead>
                 <tr>
                  <th data-field="codigo" data-filter-control="input" data-sortable="true">Codigo</th>
                   <th data-field="tipo" data-filter-control="select" data-sortable="true">Tipo</th>
                   <th data-field="descripcion" data-filter-control="input" data-sortable="true">Producto</th>
                   <th data-field="ean" data-filter-control="input" data-sortable="true">EAN</th>
                   <th data-field="proveedor" data-filter-control="select" data-sortable="true">Marca</th>
                   <th data-field="kg" data-filter-control="select" data-sortable="true">Kg</th>
                   <th data-field="arriba" data-filter-control="select" data-sortable="true">Local</th>
                   <th data-field="abajo" data-filter-control="select" data-sortable="true">Deposito</th>
                   <th data-field="precio" data-sortable="true" data-editable="true">Precio</th>
                   <th data-field="operate" >Item Price</th>
                 </tr>
               </thead>
              <tbody>
              {% for alimento in alimentos %}
                <tr>
                  <td> {{ alimento.codigo }} </td>
                  <td> {{ alimento.tipo }} </td>
                  <td> {{ alimento.descripcion }} </td>
                  <td> {{ alimento.ean }} </td>
                  <td> {{ alimento.proveedor }} </td>
                  <td> {{ alimento.kg }} </td>
                  <td> {{ alimento.arriba }} </td>
                  <td> {{ alimento.abajo }} </td>
                  <td> {{ alimento.precio }} </td>
                  <td>
                    <a href="{{ url_for('home.edit_alimento', id=alimento.codigo) }}">
                      <i class="fa fa-pencil"></i> Edit
                    </a>

                    <a href="{{ url_for('home.mover_alimento', id=alimento.codigo) }}">
                      <i class="fa fa-arrow-alt-circle-up"></i> Mover
                    </a>
                    <a href="{{ url_for('home.vender_alimento', id=alimento.codigo) }}">
                      <i class="fa fa-arrow-alt-circle-up"></i> Vender
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No alimentos have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.add_alimento') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add alimento
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table-locale-all.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="https://use.fontawesome.com/releases/v5.9.0/js/all.js" data-auto-replace-svg="nest"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
<script type="text/javascript">
var $table = $('#table');
    $(function () {
        $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
        });
    })

		var trBoldBlue = $("table");

	$(trBoldBlue).on("click", "tr", function (){
			$(this).toggleClass("bold-blue");
	});
  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }
  function operateFormatter(value, row, index) {
    return [
      '<a class="like" href="javascript:void(0)" title="Like">',
      '<i class="far fa-arrow-alt-circle-up"></i>',
      '</a>  '
    ].join('')
  }

  window.operateEvents = {
    'click .like': function (e, value, row, index) {
      if(row.abajo==0){
        alert("No se puede mover el inventario de un producto que no esta en el Deposito")
      }
      else{
        $.ajax({
          url: 'updateInventario?codigo='.concat(row.codigo),
          type:'GET',
          success:function(result){
            $table.bootstrapTable('refresh')
            alert('Se movio el inventario')
          },
          error:function(error){
            console.log('Error ${error}')
          }
        })
        // alert("Moviendo el inventario")
      }
      // alert('You click like action, row: ' + JSON.stringify(row))
    },

  }

  function detailFormatter(index, row) {
      var html = []
      $.each(row, function (key, value) {
        html.push('<p><b>' + key + ':</b> ' + value + '</p>')
      })
      return html.join('')
    }
 function initTable() {
   $table.bootstrapTable('destroy').bootstrapTable({
      height: 700,
      locale: 'en-US'
    })
  }

  $(function() {
   initTable()
 })
</script>

{% endblock %}

app/templates/home/alimentos/buscar.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Carga Codigo Barras{% endblock %}
{% block custom_css %}
<link   rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-table.min.css') }}">
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">alimentos</h1>
          <!-- <hr class="intro-divider"> -->
          <form>
            <div class="form-group col-md-4">
              <div class="col">
              <label for="ean">Codigo de Barras</label>
              <input type="text" class="form-control" id="ean" placeholder="Bar code">
            </div>
            <div class="form-group col-md-4">
              <label for="producto">descripcion</label>
              <input type="input" class="form-control" id="producto" >
            </div>
            <div class="form-group col-md-4">
              <label for="codigo">Codigo</label>
              <input type="text" class="form-control" id="codigo" >
            </div>
            </div>
          </form>
          <div class="center" style='width:75%'>
            <table
                  id="table"
                  data-toolbar="#toolbar"
                  data-pagination="true"
                  data-side-pagination="server"
                  data-query-params="queryParams"
                  data-url="../busqueda"
                  >
                 <thead>
                 <tr>
                  <th data-field="codigo"  data-sortable="true">Codigo</th>
                   <th data-field="tipo" data-sortable="true">Tipo</th>
                   <th data-field="descripcion" data-sortable="true">Producto</th>
                   <th data-field="ean"  data-sortable="true">EAN</th>
                   <th data-field="proveedor"  data-sortable="true">Marca</th>
                   <th data-field="kg"  data-sortable="true">Kg</th>
                   <th data-field="precio" data-editable="true">Precio</th>
                   <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents">Asignar</th>
                 </tr>
               </thead>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tableExport.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table-locale-all.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table-export.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/fontawesome/all.js') }}" data-auto-replace-svg="nest"></script>
<script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
<script type="text/javascript">
  var $table = $('#table');
  function initTable() {
    $table.bootstrapTable('destroy').bootstrapTable({
       height: 700,
       locale: 'en-US'
     })
   }

   $(function() {
    initTable()
  })



$(function() {
  $('#producto').keyup(function (data) {
    $table.bootstrapTable('refreshOptions', {
      showColumns: true,
      search: true,
      showRefresh: true,
      url: '../alimentos/busqueda?descripcion='+data.currentTarget.value
    })
  })
  $('#codigo').keyup(function (data) {
    $table.bootstrapTable('refreshOptions', {
      showColumns: true,
      search: true,
      showRefresh: true,
      url: '../alimentos/busqueda?codigo='+data.currentTarget.value
    })
  })
})

function operateFormatter(value, row, index) {
  return [
    '<a class="like" href="javascript:void(0)" title="Asignar">',
    '<i class="far fa-arrow-alt-circle-up"></i>',
    '</a>  '
  ].join('')
}

window.operateEvents = {
  'click .like': function (e, value, row, index) {
    var number=document.getElementById("ean").value;
    if (len(number)<10) {
      alert("No se puede actualizar el codigo, la longitud es corta")
    }
    else{
      $.ajax({
        url: 'ean',
        type:'POST',
        data:{'id':row.codigo,'ean':number},
        success:function(result){
          $table.bootstrapTable('refresh')
          alert('Actualizo el codigo de barras')
        },
        error:function(error){
          console.log('Error ${error}')
        }
      })
      // alert("Moviendo el inventario")
    }
    // alert('You click like action, row: ' + JSON.stringify(row))
  },

}
</script>

{% endblock %}

app/templates/home/alimentos/ean.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Carga Codigo Barras{% endblock %}
{% block custom_css %}
<link   rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-table.min.css') }}">
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">alimentos</h1>
          <!-- <hr class="intro-divider"> -->
          <form>
            <div class="form-group col-md-4">
              <div class="col">
              <label for="ean">Codigo de Barras</label>
              <input type="text" class="form-control" id="ean" placeholder="Bar code">
            </div>
            <div class="form-group col-md-4">
              <label for="producto">descripcion</label>
              <input type="input" class="form-control" id="producto" >
            </div>
            <div class="form-group col-md-4">
              <label for="codigo">Codigo</label>
              <input type="text" class="form-control" id="codigo" >
            </div>
            </div>
          </form>
          <div class="center" style='width:75%'>
            <table
                  id="table"
                  data-toolbar="#toolbar"
                  data-pagination="true"
                  data-side-pagination="server"
                  data-query-params="queryParams"
                  data-url="../busqueda"
                  >
                 <thead>
                 <tr>
                  <th data-field="codigo"  data-sortable="true">Codigo</th>
                   <th data-field="tipo" data-sortable="true">Tipo</th>
                   <th data-field="descripcion" data-sortable="true">Producto</th>
                   <th data-field="ean"  data-sortable="true">EAN</th>
                   <th data-field="proveedor"  data-sortable="true">Marca</th>
                   <th data-field="kg"  data-sortable="true">Kg</th>
                   <th data-field="precio" data-editable="true">Precio</th>
                   <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents">Asignar</th>
                 </tr>
               </thead>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tableExport.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table-locale-all.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-table-export.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/fontawesome/all.js') }}" data-auto-replace-svg="nest"></script>
<script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
<script type="text/javascript">
  var $table = $('#table');
  function initTable() {
    $table.bootstrapTable('destroy').bootstrapTable({
       height: 700,
       locale: 'en-US'
     })
   }

   $(function() {
    initTable()
  })



$(function() {
  $('#producto').keyup(function (data) {
    $table.bootstrapTable('refreshOptions', {
      showColumns: true,
      search: true,
      showRefresh: true,
      url: '../busqueda?descripcion='+data.currentTarget.value
    })
  })
  $('#codigo').keyup(function (data) {
    $table.bootstrapTable('refreshOptions', {
      showColumns: true,
      search: true,
      showRefresh: true,
      url: '../busqueda?codigo='+data.currentTarget.value
    })
  })
})

function operateFormatter(value, row, index) {
  return [
    '<a class="like" href="javascript:void(0)" title="Asignar">',
    '<i class="far fa-arrow-alt-circle-up"></i>',
    '</a>  '
  ].join('')
}

window.operateEvents = {
  'click .like': function (e, value, row, index) {
    var number=document.getElementById("ean").value;
    if (len(number)<10) {
      alert("No se puede actualizar el codigo, la longitud es corta")
    }
    else{
      $.ajax({
        url: 'ean',
        type:'POST',
        data:{'id':row.codigo,'ean':number},
        success:function(result){
          $table.bootstrapTable('refresh')
          alert('Actualizo el codigo de barras')
        },
        error:function(error){
          console.log('Error ${error}')
        }
      })
      // alert("Moviendo el inventario")
    }
    // alert('You click like action, row: ' + JSON.stringify(row))
  },

}
</script>

{% endblock %}