app/home/forms.py
# Forms for admin blueprint
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,IntegerField,FloatField
from wtforms.validators import DataRequired


class AlimentoForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    codigo = StringField('Codigo', validators=[DataRequired()])
    tipo = StringField('Tipo', validators=[DataRequired()])
    categoria = StringField('Categoria')
    proveedor = StringField('Proveedor', validators=[DataRequired()])
    descripcion = StringField('Descripcion', validators=[DataRequired()])
    kg = StringField('Peso')
    precio = FloatField('Precio')
    ean = StringField('ean')
    arriba = IntegerField('Local')
    abajo = IntegerField('Deposito')
    submit = SubmitField('Submit')

class EanForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    ean = StringField('EAN', validators=[DataRequired()])
    producto = StringField('Description')
    codigo = StringField('Codigo')
    submit = SubmitField('Submit')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, flash, redirect, render_template, url_for,jsonify,request,send_file
from flask_login import current_user, login_required
import pandas as pd
from sqlalchemy.inspection import inspect
from xlsxwriter import Workbook
#import flask_excel as excel

from . import home

from .forms import AlimentoForm,EanForm
from .. import db
from ..models import Alimento, Venta
from datetime import datetime

def query_to_list(rset):
    """List of result
    Return: columns name, list of result
    """
    result = []
    for obj in rset:
        instance = inspect(obj)
        items = instance.attrs.items()
        result.append([x.value for _,x in items])
    return instance.attrs.keys(), result
@home.route('/')
def homepage():
    """
    Render the homepage template on the / route adslangldsng l
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/alimentos', methods=['GET', 'POST'])
def list_alimentos():
    """
    List all alimentos
    """

    alimentos = Alimento.query.all()

    return render_template('home/alimentos/alimentos.html',
                           alimentos=alimentos, title="Alimento")


@home.route('/alimentos/add', methods=['GET', 'POST'])
def add_alimento():
    """
    Add a alimento to the database
    """
    add_alimento = True

    form = AlimentoForm()
    if form.validate_on_submit():
        alimento = Alimento(tipo = form.tipo.data,codigo = form.codigo.data
                                ,categoria = form.categoria.data,proveedor = form.proveedor.data,descripcion = form.descripcion.data
                                ,kg = form.kg.data,precio = form.precio.data,ean = form.ean.data,arriba = form.arriba.data
                                ,abajo = form.abajo.data)
        try:
            # add alimento to the database
            db.session.add(alimento)
            db.session.commit()
            flash('You have successfully added a new alimento.')
        except:
            # in case alimento name already exists
            flash('Error: alimento name already exists.')

        # redirect to alimentos page
        return redirect(url_for('home.list_alimentos'))

    # load alimento template
    return render_template('home/alimentos/alimento.html', action="Add",
                           add_alimento=add_alimento, form=form,
                           title="Add alimento")


@home.route('/alimentos/edit/<id>', methods=['GET', 'POST'])
def edit_alimento(id):
    """
    Edit a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    form = AlimentoForm(obj=alimento)
    if form.validate_on_submit():
        alimento.tipo = form.tipo.data
        alimento.categoria = form.categoria.data
        alimento.proveedor = form.proveedor.data
        alimento.descripcion = form.descripcion.data
        alimento.kg = form.kg.data
        alimento.precio = form.precio.data
        alimento.ean = form.ean.data
        alimento.arriba = form.arriba.data
        alimento.abajo = form.abajo.data
        db.session.commit()
        flash('You have successfully edited the alimento.')

        # redirect to the alimentos page
        return redirect(url_for('home.list_alimentos'))

    form.tipo.data=alimento.tipo
    form.categoria.data= alimento.categoria
    form.proveedor.data= alimento.proveedor
    form.descripcion.data= alimento.descripcion
    form.kg.data= alimento.kg
    form.precio.data= alimento.precio
    form.ean.data= alimento.ean
    form.arriba.data= alimento.arriba
    form.abajo.data= alimento.abajo
    return render_template('home/alimentos/alimento.html', action="Edit",
                           add_alimento=add_alimento, form=form,
                           alimento=alimento, title="Edit alimento")


@home.route('/alimentos/delete/<id>', methods=['GET', 'POST'])
def delete_alimento(id):
    """
    Delete a alimento from the database
    """
    check_home()

    alimento = alimento.query.get_or_404(id)
    db.session.delete(alimento)
    db.session.commit()
    flash('You have successfully deleted the alimento.')

    # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

    return render_template(title="Delete alimento")


@home.route('/alimentos/inventario/<id>', methods=['GET', 'POST'])
def mover_alimento(id):
    """
    Edit a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    alimento.arriba = int(alimento.arriba)+1
    alimento.abajo = int(alimento.abajo)-1
    db.session.commit()
    flash('You have successfully edited the alimento.')

        # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

@home.route('/alimentos/vender/<id>', methods=['GET', 'POST'])
def vender_alimento(id):
    """
    Vender a alimento
    """

    add_alimento = False

    alimento = Alimento.query.get_or_404(id)
    if alimento.arriba >0:
        alimento.arriba = int(alimento.arriba)-1
    else:
        alimento.abajo = int(alimento.abajo)-1
    db.session.commit()

    venta = Venta(codigo=id,tipo =alimento.tipo,    categoria = alimento.categoria,    proveedor = alimento.proveedor,    descripcion = alimento.descripcion,    kg = alimento.kg,    precio = alimento.precio,    ean = alimento.ean)
    try:
        # add alimento to the database
        db.session.add(venta)
        db.session.commit()
        flash('You have successfully added a new venta.')
    except Exception as inst :
        # in case alimento name already exists
        print(str(inst))
        flash('Error: no se pudo procesar la venta')

        # redirect to the alimentos page
    return redirect(url_for('home.list_alimentos'))

@home.route('/alimentos/ean/', methods=['GET', 'POST'])
def add_ean():
    """
    Add a alimento to the database
    """
    if request.method == 'POST':
        alimento = Alimento.query.get_or_404(id)
        alimento.ean = request.values.get('ean')
        db.session.commit()
        flash('You have successfully edited the alimento.')

    # load alimento template
    return render_template('home/alimentos/ean.html',
                           title="Agregar Ean")
@home.route('/alimentos/busqueda', methods=['GET', 'POST'])
def busqueda():
    if request.args.get('codigo') != None and len(request.args.get('codigo') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.codigo.like("%"+request.args.get('codigo')+"%")).all())
    elif request.args.get('descripcion') != None and len(request.args.get('descripcion') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.descripcion.like("%"+request.args.get('descripcion')+"%")).all())
    else:
        #names, data = query_to_list(Alimento.query.all())
        return  jsonify({"total": 0,'rows':[]})
    df = pd.DataFrame.from_records(data, columns=names)
    output=df[['descripcion', 'codigo', 'tipo', 'arriba', 'abajo','proveedor','precio','kg','categoria']].to_dict('records')
    return  jsonify({"total": len(output), "totalNotFiltered": 800,'rows':output})


@home.route('/alimentos/stock', methods=['GET', 'POST'])
def update_stock():
    if request.args.get('codigo') != None and len(request.args.get('codigo') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.codigo.like("%"+request.args.get('codigo')+"%")).all())
    elif request.args.get('descripcion') != None and len(request.args.get('descripcion') ) >2:
        names, data = query_to_list(Alimento.query.filter(Alimento.descripcion.like("%"+request.args.get('descripcion')+"%")).all())
    else:
        #names, data = query_to_list(Alimento.query.all())
        return  jsonify({"total": 0,'rows':[]})
    df = pd.DataFrame.from_records(data, columns=names)
    output=df[['descripcion', 'codigo', 'tipo', 'arriba', 'abajo','proveedor','precio','kg','categoria']].to_dict('records')
    return  jsonify({"total": len(output), "totalNotFiltered": 800,'rows':output})

@home.route('/alimentos/subir', methods=['GET','POST'])
def subir_productos():
    if request.method == 'POST':
        df=pd.DataFrame.from_dict(request.get_array(field_name='file'))
        df.columns=df.iloc[0]
        df=df.drop(0)
        df.set_index('codigo',inplace=True)
        df.to_sql('alimento', if_exists='replace',con=db.engine)
        return redirect(url_for('home.list_alimentos'))

        return jsonify({"result":request.get_array(field_name='file')})
    return '''
    <!doctype html>
    <title>Upload an excel file</title>
    <h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    <form action="" method=post enctype=multipart/form-data><p>
    <input type=file name=file><input type=submit value=Upload>
    </form>
    '''

@home.route('/alimentos/descargar', methods=['GET','POST'])
def descargar_productos():
    now = datetime.now()
    # return excel.make_response_from_tables(db.session,[Alimento,Venta],'xlsx',file_name='productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")))
    result = db.engine.execute("select * from alimento")
    df=pd.DataFrame(result.fetchall())
    writer1 = pd.ExcelWriter('productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")), engine='xlsxwriter')
    df.to_excel(writer1, sheet_name='name of sheet 1', index=False, startrow=0)
    writer1.save()
    return send_file('../productos_{}'.format(now.strftime("%m_%d_%Y_%H%M%S")))

    #
@home.route('/alimentos/buscar', methods=['GET', 'POST'])
def buscar():

    return render_template('home/alimentos/buscar.html',
                           title="Buscar")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Project Dream Team</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    {% block custom_css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Project Dream Team</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('home.list_alimentos') }}">Listado</a></li>
                  <li><a href="{{ url_for('home.buscar') }}">Buscar</a></li>
                  <li><a href="{{ url_for('home.add_ean') }}">Codigo De Barra</a></li>
                  <li><a href="{{ url_for('home.descargar_productos') }}">Descargas</a></li>
                  <li><a href="{{ url_for('home.subir_productos') }}">Subir</a></li>
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="#">Register</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="#">Login</a></li>
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
{% block js %}
{% endblock %}
</html>

app/templates/home.html
<html>
  <body>
    <form method="POST" action="/">
      <input type="text" name="title">
      <input type="submit" value="Add">
    </form>
  </body>
</html>

app/templates/search.html
<head>
<link   rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link   rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.min.css">
<link   rel="stylesheet" href="//rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/css/bootstrap-editable.css">
<style media="screen">
  .container {
	width: 1024px;
	padding: 2em;
}

.bold-blue {
	font-weight: bold;
	color: #0277BD;
}
</style>
<body>


<div class="container">
<h1>Bootstrap Table</h1>
<p> Mémo pour les options du Bootstrap Table : <a href="http://bootstrap-table.wenzhixin.net.cn/documentation/">Bootstrap Table Documentation</a></p>
<p>Eléments de Bootstrap Table utilisés : <a href="http://jsfiddle.net/wenyi/e3nk137y/3178/">Data Checkbox</a>, pour cocher les éléments à sélectionner, <a href="https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/filter-control.html">extension Filter control</a>, pour les filtres via les colonnes, <a href="https://github.com/kayalshri/tableExport.jquery.plugin">extension Data export</a> pour exporter</p>

<div id="toolbar">
		<select class="form-control">
				<option value="">Export Basic</option>
				<option value="all">Export All</option>
				<option value="selected">Export Selected</option>
		</select>
</div>
<table
     id="table"
     data-toolbar="#toolbar"
 data-search="true"
 data-show-refresh="true"
 data-show-toggle="true"
 data-show-fullscreen="true"
 data-show-columns="true"
 data-show-export="true"
     data-minimum-count-columns="2"
  data-show-pagination-switch="true"
  data-pagination="true"
     data-filter-control="true"
     data-pagination="true"
     data-page-list="[10, 25, 50, 100, ALL]"
     data-url="data">
     <thead>
     <tr>
       <th data-field="state" data-checkbox="true"></th>
       <th data-field="tipo" data-filter-control="select" data-sortable="true">Tipo</th>
       <th data-field="descripcion" data-filter-control="input" data-sortable="true">Producto</th>
       <th data-field="proveedor" data-filter-control="select" data-sortable="true">Marca</th>
       <th data-field="kg" data-filter-control="select" data-sortable="true">Kg</th>
       <th data-field="arriba" data-filter-control="select" data-sortable="true">Local</th>
       <th data-field="abajo" data-filter-control="select" data-sortable="true">Deposito</th>
       <th data-field="precio" data-sortable="true" data-editable="true">Precio</th>
       <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents">Item Price</th>
     </tr>
   </thead>
  <!-- </table>

<table id="table"
			 data-toggle="table"
			 data-search="true"
			 data-filter-control="true"
			 data-show-export="true"
			 data-click-to-select="true"
			 data-toolbar="#toolbar">
	 <thead>
		<tr>
			<th data-field="state" data-checkbox="true"></th>
			<th data-field="producto" data-filter-control="input" data-sortable="true">Producto</th>
			<th data-field="marca" data-filter-control="select" data-sortable="true">Marca</th>
			<th data-field="stock" data-filter-control="select" data-sortable="true">Stpck</th>
			<th data-field="precio" data-sortable="true">Precio</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="bs-checkbox "><input data-index="0" name="btSelectItem" type="checkbox"></td>
			<td>Valérie</td>
			<td>01/09/2015</td>
			<td>Français</td>
			<td>12/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="1" name="btSelectItem" type="checkbox"></td>
			<td>Eric</td>
			<td>05/09/2015</td>
			<td>Philosophie</td>
			<td>8/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="2" name="btSelectItem" type="checkbox"></td>
			<td>Valentin</td>
			<td>05/09/2015</td>
			<td>Philosophie</td>
			<td>4/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="3" name="btSelectItem" type="checkbox"></td>
			<td>Valérie</td>
			<td>05/09/2015</td>
			<td>Philosophie</td>
			<td>10/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="4" name="btSelectItem" type="checkbox"></td>
			<td>Eric</td>
			<td>01/09/2015</td>
			<td>Français</td>
			<td>14/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="5" name="btSelectItem" type="checkbox"></td>
			<td>Valérie</td>
			<td>07/09/2015</td>
			<td>Mathématiques</td>
			<td>19/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="6" name="btSelectItem" type="checkbox"></td>
			<td>Valentin</td>
			<td>01/09/2015</td>
			<td>Français</td>
			<td>11/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="7" name="btSelectItem" type="checkbox"></td>
			<td>Eric</td>
			<td>01/10/2015</td>
			<td>Philosophie</td>
			<td>8/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="8" name="btSelectItem" type="checkbox"></td>
			<td>Valentin</td>
			<td>07/09/2015</td>
			<td>Mathématiques</td>
			<td>14/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="9" name="btSelectItem" type="checkbox"></td>
			<td>Valérie</td>
			<td>01/10/2015</td>
			<td>Philosophie</td>
			<td>12/20</td>
		</tr>
		<tr>
			<td class="bs-checkbox "><input data-index="10" name="btSelectItem" type="checkbox"></td>
			<td>Eric</td>
			<td>07/09/2015</td>
			<td>Mathématiques</td>
			<td>14/20</td>
		</tr>
		<tr>
		<td class="bs-checkbox "><input data-index="11" name="btSelectItem" type="checkbox"></td>
			<td>Valentin</td>
			<td>01/10/2015</td>
			<td>Philosophie</td>
			<td>10/20</td>
		</tr>
	</tbody>
</table>-->
</div>
</body>

 <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
 <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
 <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>
 <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table-locale-all.min.js"></script>
 <script src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script src="https://use.fontawesome.com/releases/v5.9.0/js/all.js" data-auto-replace-svg="nest"></script>
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

<script type="text/javascript">
var $table = $('#table');
    $(function () {
        $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
        });
    })

		var trBoldBlue = $("table");

	$(trBoldBlue).on("click", "tr", function (){
			$(this).toggleClass("bold-blue");
	});
  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }
  function operateFormatter(value, row, index) {
    return [
      '<a class="like" href="javascript:void(0)" title="Like">',
      '<i class="far fa-arrow-alt-circle-up"></i>',
      '</a>  '
    ].join('')
  }

  window.operateEvents = {
    'click .like': function (e, value, row, index) {
      if(row.abajo==0){
        alert("No se puede mover el inventario de un producto que no esta en el Deposito")
      }
      else{
        $.ajax({
          url: 'updateInventario?codigo='.concat(row.codigo),
          type:'GET',
          success:function(result){
            $table.bootstrapTable('refresh')
            alert('Se movio el inventario')
          },
          error:function(error){
            console.log('Error ${error}')
          }
        })
        // alert("Moviendo el inventario")
      }
      // alert('You click like action, row: ' + JSON.stringify(row))
    },

  }

  function detailFormatter(index, row) {
      var html = []
      $.each(row, function (key, value) {
        html.push('<p><b>' + key + ':</b> ' + value + '</p>')
      })
      return html.join('')
    }
 function initTable() {
   $table.bootstrapTable('destroy').bootstrapTable({
      height: 550,
      locale: 'es-AR'
    })
  }

  $(function() {
   initTable()
 })
</script>


</head>